### ISSUE TITLE
Failed to Open RTL Device 

### ISSUE THREAD

**Issue by kc9pos** [evanmayer/effex#11]
Hello I have a question regarding freeing up the resources of the sdr receiver after the effex.py script runs. I try rerunning the script after running it the first time and I get the error 
Found 2 device(s):
  0:  RTL-SDR, KerberosSDR, SN: 003
  1:  RTL-SDR, KerberosSDR, SN: 004

Using device 0: Generic RTL2832U OEM
usb_claim_interface error -6
Failed to open rtlsdr device #0.

I usually have to reboot my nano board to free it up?

**Comment by evanmayer** [comment]
This is a "problem" with RTL-SDRs in general, and the RTL-SDR driver/libusb, not specifically with my code. [It is caused by another process having the claim to the USB device you're trying to use.](https://lmgtfy.app/?q=rtl+sdr+usb+claim+interface+error+6) This can occur when a program using an RTL-SDR crashes or does not exit cleanly, leaving behind a "zombie" process that still hangs onto the device. 

You can resolve this by either disconnecting and reconnecting the USB cable into the Jetson, or you can solve it with a reboot.

I try to ensure my program doesn't hang onto devices by closing them when an exception is caught during a run. If there is a crash occurring *inside my code* (a backtrace indicates the problem occurred at its lowest level in `effex.py`) and the exception is not handled in this way, let me know and I will consider this an issue with `effex` code.

**Comment by kc9pos** [comment]
Sweet thank you I am running everything in jupyter notebook and found that happening.
